Repository davecharm16/supa_app_deliver, pull requests merged in 2024-05, with the labels that each got.

#2 chore(templates): added ftttemplate and analysis option yamel
  .fttemplates/.ftsettings.json
  .fttemplates/data/apis/[FTName]_api_service.dart
  .fttemplates/data/repositories/[FTName]_repository.dart
  .fttemplates/ddd module/data/apis/[FTName]_api_service.dart
  .fttemplates/ddd module/data/repositories/[FTName]_repository.dart
  .fttemplates/ddd module/domain/cubit/[FTName]_cubit.dart
  .fttemplates/ddd module/domain/cubit/[FTName]_state.dart
  .fttemplates/ddd module/domain/repositories/i_[FTName]_repository.dart
  .fttemplates/ddd module/presentation/[FTName]_screen.dart
  .fttemplates/domain/cubit/[FTName]_cubit.dart
  .fttemplates/domain/cubit/[FTName]_state.dart
  .fttemplates/domain/repositories/i_[FTName]_repository.dart
  .fttemplates/presentation/[FTName]_screen.dart
  .gitignore
  analysis_options.yaml
Labels: chore

#3 build(Localizations): added l10n to the project
  l10n.yaml
  lib/app/app.dart
  lib/feature/auth/presentation/login_screen.dart
  lib/l10n/arb/app_en.arb
  lib/l10n/l10n.dart
  pubspec.lock
  pubspec.yaml
Labels: chore

#4 Chore/asset gen
  lib/feature/auth/presentation/login_screen.dart
  lib/l10n/arb/app_en.arb
  pubspec.lock
  pubspec.yaml
Labels: chore

#5 Feat/App-Utils
  lib/app/app.dart
  lib/app/presentation/utils/app_colors.dart
  lib/app/presentation/utils/text_styles.dart
  pubspec.lock
  pubspec.yaml
Labels: chore, Feature

#6 feat(Supa Buttons): added different supa buttons and styles
  lib/app/presentation/utils/app_colors.dart
  lib/app/presentation/utils/button_styles.dart
  lib/app/presentation/utils/text_styles.dart
  lib/app/presentation/widgets/supa_buttons.dart
Labels: Feature
